# Generated by Django 4.0.6 on 2022-08-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_league_remove_player_team_player_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['last_name']},
        ),
        migrations.RemoveField(
            model_name='league',
            name='abbrev',
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_score', models.SmallIntegerField()),
                ('away_score', models.SmallIntegerField()),
                ('penalty_dec', models.BooleanField()),
                ('no_winner', models.BooleanField()),
                ('recorded', models.BooleanField()),
                ('link_1', models.URLField()),
                ('link_2', models.URLField()),
                ('link_3', models.URLField()),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_games', to='actions.team')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_games', to='actions.team')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasons', to='actions.season')),
                ('team_lose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lose_games', to='actions.team')),
                ('team_won', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='actions.team')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
