# Generated by Django 4.0.6 on 2022-08-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_game_league_alter_game_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='abbrev',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
