# Generated by Django 4.0.6 on 2022-08-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_league_abbrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link_1',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='link_2',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='link_3',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='no_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='penalty_dec',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='recorded',
            field=models.BooleanField(default=False),
        ),
    ]
