# Generated by Django 4.0.6 on 2022-08-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_squad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='squad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='squad_teams', to='actions.squad'),
        ),
    ]
