# Generated by Django 4.0.6 on 2022-08-10 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0010_type_alter_squad_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='video_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
            preserve_default=False,
        ),
    ]
