# Generated by Django 4.0.6 on 2022-08-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_action_video_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/logos'),
        ),
    ]
