# Generated by Django 4.0.6 on 2022-08-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0014_alter_game_link_1_alter_game_link_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['name_cz']},
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, related_name='players', to='actions.team'),
        ),
    ]
