# Generated by Django 4.0.6 on 2022-09-11 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0016_remove_player_team_player_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='left_pitch_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_pitch_teams', to='actions.team'),
        ),
        migrations.AddField(
            model_name='action',
            name='right_pitch_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_pitch_teams', to='actions.team'),
        ),
        migrations.AlterField(
            model_name='action',
            name='active_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_player_actions', to='actions.player'),
        ),
        migrations.AlterField(
            model_name='action',
            name='passive_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passive_player_actions', to='actions.player'),
        ),
    ]
