# Generated by Django 4.0.6 on 2022-09-12 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0017_action_left_pitch_team_action_right_pitch_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team_possession',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='game',
            name='extra_time_dec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_possession',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
