# Generated by Django 4.0.6 on 2022-09-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0018_game_away_team_possession_game_extra_time_dec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='side',
            field=models.IntegerField(blank=True, choices=[(1, 'Left'), (2, 'Right')], null=True),
        ),
    ]
