# Generated by Django 4.0.6 on 2022-09-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0019_action_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(db_collation='cs_CZ.UTF-8', max_length=64),
        ),
    ]
