# Generated by Django 4.0.6 on 2022-10-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0020_alter_player_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(db_collation='cs_CZ', max_length=64),
        ),
    ]
